name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign APK
        if: secrets.RELEASE_KEYSTORE != ''
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > release.keystore
          find "$ANDROID_SDK_ROOT/build-tools" -type f -name "apksigner" | sort -r | head -n 1 | xargs -I {} {} sign \
            --ks release.keystore \
            --ks-key-alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.RELEASE_KEY_PASSWORD }}" \
            --out app/build/outputs/apk/release/app-release-signed.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Create Release
        if: secrets.RELEASE_KEYSTORE != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: app/build/outputs/apk/release/app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Unsigned APK as Artifact
        if: secrets.RELEASE_KEYSTORE == ''
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
